name: Deploy to Remote Server
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - dev

jobs:
  build:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN }}/triptip_frontend:latest

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Executing remote ssh to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/triptip_backend
            sudo docker compose -f deploy-compose.yaml down
            sudo docker compose -f deploy-compose.yaml pull
            sudo docker compose -f deploy-compose.yaml build --no-cache
            sudo docker compose -f deploy-compose.yaml up -d
