name: Deploy to Remote Server
run-name: Push to ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    branches:
      - master

permissions:
    statuses: write

jobs:
  build:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_LOGIN }}/triptip_frontend:latest

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Executing remote ssh to deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/triptip_backend
            sudo docker compose -f deploy-compose.yaml down
            sudo docker compose -f deploy-compose.yaml pull
            sudo docker compose -f deploy-compose.yaml build --no-cache
            sudo docker compose -f deploy-compose.yaml up -d

  notify:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Determine job status
          id: job_status
          run: echo "JOB_STATUS=success" >> $GITHUB_ENV
          if: success()
  
        - name: Set job status to failure
          run: echo "JOB_STATUS=failure" >> $GITHUB_ENV
          if: failure()
          continue-on-error: true
  
        - name: Send Telegram message on job status
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              🚀 Deploy to prod was ${{ env.JOB_STATUS }}!
              - GitHub Triggering Actor: ${{ github.actor }}
              - Run ID: ${{ github.run_id }}
              - Commit: ${{ github.sha }}
              - GitHub Ref Name: ${{ github.ref_name }}
              - GitHub Repository: ${{ github.repository }}
          if: always()